name: Build and Run Java Application in Docker

on:
  push:
    branches:
      - main

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: java

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package
    - name: Test with Maven
      run: mvn test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: target/helloworld-1.0-SNAPSHOT.jar
    - name: Run Application
      run: java -cp target/helloworld-1.0-SNAPSHOT.jar com.example.App

  run:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: target/

    - name: List target directory
      run: ls -la target

    - name: Build Docker image
      run: docker build -t helloworld-app .

    - name: Run Docker container
      run: docker run --name helloworld-container helloworld-app